services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "7878:7878"

  client:
    profiles: ["client"]
    build:
      context: .
      dockerfile: client/Dockerfile
    stdin_open: true
    tty: true
